service: kinesis-consumer

frameworkVersion: '>=1.0.0 <2.0.0'

custom:
  defaultStage: 'dev'

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:provider.environment.awsRegion}
  environment: ${file(../env.yml)}

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

resources:
  Resources:
    kinesisConsumerTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: ${self:provider.environment.kinesisConsumerTable}-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: eventID
            AttributeType: S
        KeySchema:
          - AttributeName: eventID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn:
        - kinesisConsumerTable
      Properties:
        PolicyName: lambda-${self:service}-${self:provider.stage}-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: 'arn:aws:dynamodb:${self:provider.region}:#{AWS::AccountId}:table/${self:provider.environment.kinesisConsumerTable}-${self:provider.stage}'
            - Effect: Allow
              Action:
                - kinesis:GetRecords
                - kinesis:GetShardIterator
                - kinesis:DescribeStream,
                - kinesis:ListStreams
              Resource: 'arn:aws:kinesis:${self:provider.region}:#{AWS::AccountId}:stream/${self:provider.environment.kinesisStreamName}'
        Roles:
          - Ref: IamRoleLambdaExecution

functions:
  consume:
    handler: consumer.consume
    events:
      - stream:
          arn: 'arn:aws:kinesis:${self:provider.region}:#{AWS::AccountId}:stream/${self:provider.environment.kinesisStreamName}'
          batchSize: 100
          startingPosition: LATEST
          enabled: true