service: kinesis-consumer

frameworkVersion: '>=1.0.0 <2.0.0'

custom:
  defaultStage: 'dev'

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-southeast-2
  environment: ${file(../env.yml)}

plugins:
  - serverless-webpack

functions:
  consume:
    handler: consumer.consume